behaviors:
  CarAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 1.0e-5
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.5
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      gail:
        strength: 0.5
        demo_path: D:/Unity Projects/Xtreme Racing/Car AI Demos/Car-Simple-Obstacle-With-Speedbreakers-And-Track-Edge-Speed-Reduction.demo
    behavioral_cloning:
       strength: 0.5
       demo_path: D:/Unity Projects/Xtreme Racing/Car AI Demos/Car-Simple-Obstacle-With-Speedbreakers-And-Track-Edge-Speed-Reduction.demo
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 25000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true
    self_play: null
    